#!/bin/bash
# install - installs dotfiles to your home directory

# Exit on error
set -e

# You probably don't want to do this as root
if [ $USER = "root" ]; then
    echo "I can't let you do that."
    exit 1
fi

# Make symbolic links to this directory
for TARGET in .bashrc .bash_aliases .bash_profile .vimrc .vim; do
    ln -s --force --no-dereference --verbose "$PWD/$TARGET" "$HOME/$TARGET"
done

#" vim: filetype=sh
