#!/bin/bash

if [[ $# -ne 1 ]]
then
    echo "express_coffee: Usage: express_coffee <name-of-project>\n"
    echo "Number of arguments: $#\n";
    exit 1
fi

express $1
js2coffee "$1/app.js" > "$1/app.coffee"
js2coffee "$1/routes/routes.js" > "$1/routes/routes.coffee"
